description: Keeps track of your studies
name: mahschema

dependencies:
  tuple: "^1.0.1"
  flutter_color_picker: "^0.0.1"
  redux: "^1.1.0"
  flutter_stream_friends: "^0.5.0"
  http: '>=0.11.3+12'
  rxdart:
    git: "https://github.com/ReactiveX/rxdart.git"
  path_provider: "^0.2.1+1"
  dslink_schedule:
    git: "https://github.com/IOT-DSA/dslink-dart-schedule.git"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/mah.jpg
    - assets/images/logo.jpg


